import {
  AssetsState,
  BridgeCreditScoreState,
  BridgePurchaseState,
  BridgeRefinanceState,
  CreditScoreState,
  DTIState,
  MortgagePurchaseState,
  MortgageRefinanceAssetsState,
  MortgageRefinanceState,
  StartingState,
} from '@/types/enum';
import {
  PipelineTaskItemStatus,
  PipelineTaskKey,
  PipelineTaskName,
} from '@/types/pipeline';
import { Options } from '@/types/options';

export const FormData = {
  mortgage: {
    purchase: {
      name: 'MortgagePurchase',
      preApproved: false,
      denialReason: void 0,
      state: MortgagePurchaseState.starting,
      starting: {
        purpose: {
          values: {
            stageOpt: Options.ProcessOpt.default,
            offerOpt: Options.OfferOpt.default,
            purchaseTimeOpt: Options.PurchaseTimeOpt.default,
            address: {
              formatAddress: '',
              aptNumber: '',
              state: '',
              street: '',
              city: '',
              postcode: '',
              errors: {},
              isValid: false,
            },
            isValid: false,
          },
        },
        property: {
          values: {
            occupancyOpt: Options.OccupancyOpt.default,
            propertyOpt: Options.PropertyOpt.default,
            rentalIncome: undefined,
            numberOfUnits: Options.PropertyUnitOpt.default,
          },
          errors: {},
          isValid: false,
        },
        state: StartingState.purpose,
      },
      creditScore: {
        values: {
          selfInfo: {
            firstName: '',
            lastName: '',
            phoneNumber: '',
            dateOfBirth: null,
            address: {
              formatAddress: '',
              aptNumber: '',
              state: '',
              street: '',
              city: '',
              postcode: '',
              errors: {},
              isValid: false,
            },
            ssn: '',
            email: '',
            authorizedCreditCheck: false,
            creditScore: 799,
            errors: {},
            isValid: false,
          },
          selfIncome: {
            salary: {
              annualSalary: undefined,
              bonuses: undefined,
              stock: undefined,
            },
            selfEmployed: {
              annualProfit: undefined,
              annualPaySelf: undefined,
            },
            socialSecurity: {
              totalIncome: undefined,
            },
            other: {
              monthlyChildSupport: undefined,
              monthlyAlimony: undefined,
              other: undefined,
            },
          },
          coBorrower: {
            hasCoOwners: undefined,
            hasCoBorrower: undefined,
            readyEnter: undefined,
          },
          coBorrowerRelationship: {
            relationship: Options.RelationshipOpt.default,
            liveTogether: undefined,
            willLiveTogether: undefined,
          },
          coBorrowerInfo: {
            firstName: '',
            lastName: '',
            phoneNumber: '',
            dateOfBirth: null,
            address: {
              formatAddress: '',
              aptNumber: '',
              state: '',
              street: '',
              city: '',
              postcode: '',
              errors: {},
              isValid: false,
            },
            ssn: '',
            authorizedCreditCheck: false,
            creditScore: 799,
            errors: {},
            isValid: false,
          },
          coBorrowerIncome: {
            salary: {
              annualSalary: undefined,
              bonuses: undefined,
              stock: undefined,
            },
            selfEmployed: {
              annualProfit: undefined,
              annualPaySelf: undefined,
            },
            socialSecurity: {
              totalIncome: undefined,
            },
            other: {
              monthlyChildSupport: undefined,
              monthlyAlimony: undefined,
              other: undefined,
            },
          },
          borrowerDebts: [],
          coBorrowerDebts: [],
        },
        debtsTableState: false,
        payoffTableState: false,
        state: CreditScoreState.notice,
      },
      DTI: {
        state: DTIState.notice,
        dti: 0,
        reconciled: false,
        dtiMaxAcceptable: 0.43,
      },
      assets: {
        realEstateEditState: 'view',
        everOwnedEstate: undefined,
        ownCurrentEstate: undefined,
        ownOtherEstate: undefined,
        currentEstate: {
          isCurrentEstate: true,
          address: {
            formatAddress: '236 Kingfisher Avenue, Alameda, CA 94501',
            aptNumber: '',
            state: '',
            street: '',
            city: '',
            postcode: '',
            errors: undefined,
            isValid: false,
          },
          expectSellPrice: undefined,
          expectRentPrice: undefined,
          sellForPurchaseNew: undefined,
          hasMonthlyPayment: undefined,
          propertyTitle: Options.PropertyTitleOpt.default,
          propertyPlan: Options.PropertyPlanOpt.default,
          propertyPurpose: Options.PropertyPurposeOpt.default,
          loanList: [],
          interestedRefinancing: undefined,
        },
        realEstateList: [],
        financialSituation: {
          savingAccount: undefined,
          retirementAccount: undefined,
          stockAndBonds: undefined,
          giftFromRelative: undefined,
          loanAmount: undefined,
          salesOfRealEstate: undefined,
          other: undefined,
        },
        purchasePrice: undefined,
        downPayment: undefined,
        state: AssetsState.currentEstate,
        propertyPriceValid: false,
      },
      realtor: {
        firstName: '',
        lastName: '',
        email: '',
        phoneNumber: '',
        errors: {},
        isValid: false,
        isSkip: false,
      },
    },
    refinance: {
      name: 'MortgageRefinance',
      preApproved: false,
      denialReason: void 0,
      state: MortgageRefinanceState.starting,
      starting: {
        purpose: {
          values: {
            address: {
              formatAddress: '',
              aptNumber: '',
              state: '',
              street: '',
              city: '',
              postcode: '',
              errors: {},
              isValid: false,
            },
            isValid: false,
          },
        },
        property: {
          values: {
            homeValue: undefined,
            occupancyOpt: Options.OccupancyOpt.default,
            propertyOpt: Options.PropertyOpt.default,
            numberOfUnits: Options.PropertyUnitOpt.default,
            rentalIncome: undefined,
          },
          errors: {},
          isValid: false,
        },
        state: StartingState.purpose,
      },
      creditScore: {
        values: {
          selfInfo: {
            firstName: '',
            lastName: '',
            phoneNumber: '',
            dateOfBirth: null,
            address: {
              formatAddress: '',
              aptNumber: '',
              state: '',
              street: '',
              city: '',
              postcode: '',
              errors: {},
              isValid: false,
            },
            ssn: '',
            email: '',
            authorizedCreditCheck: false,
            creditScore: 799,
            errors: {},
            isValid: false,
          },
          selfIncome: {
            salary: {
              annualSalary: undefined,
              bonuses: undefined,
              stock: undefined,
            },
            selfEmployed: {
              annualProfit: undefined,
              annualPaySelf: undefined,
            },
            socialSecurity: {
              totalIncome: undefined,
            },
            other: {
              monthlyChildSupport: undefined,
              monthlyAlimony: undefined,
              other: undefined,
            },
          },
          coBorrower: {
            hasCoOwners: undefined,
            hasCoBorrower: undefined,
            readyEnter: undefined,
          },
          coBorrowerRelationship: {
            relationship: Options.RelationshipOpt.default,
            liveTogether: undefined,
            willLiveTogether: undefined,
          },
          coBorrowerInfo: {
            firstName: '',
            lastName: '',
            phoneNumber: '',
            dateOfBirth: null,
            address: {
              formatAddress: '',
              aptNumber: '',
              state: '',
              street: '',
              city: '',
              postcode: '',
              errors: {},
              isValid: false,
            },
            ssn: '',
            authorizedCreditCheck: false,
            creditScore: 799,
            errors: {},
            isValid: false,
          },
          coBorrowerIncome: {
            salary: {
              annualSalary: undefined,
              bonuses: undefined,
              stock: undefined,
            },
            selfEmployed: {
              annualProfit: undefined,
              annualPaySelf: undefined,
            },
            socialSecurity: {
              totalIncome: undefined,
            },
            other: {
              monthlyChildSupport: undefined,
              monthlyAlimony: undefined,
              other: undefined,
            },
          },
          borrowerDebts: [],
          coBorrowerDebts: [],
        },
        borrowerDebtsTableState: undefined,
        borrowerPayoffTableState: undefined,
        coBorrowerDebtsTableState: undefined,
        coBorrowerPayoffTableState: undefined,
        state: CreditScoreState.notice,
      },
      monthlyPayment: {
        hasMonthlyPayment: undefined,
        loanList: [],
      },
      assets: {
        values: {
          residenceOwn: {
            ownCurrentEstate: undefined,
            hasMonthlyPayment: undefined,
            payments: [],
            propertyTitle: Options.PropertyTitleOpt.default,
          },
          yourProperty: [],
          whyRefinance: {
            purpose: Options.WhyRefinanceOpt.default,
            cashOut: undefined,
            payments: [],
            hasMonthlyPayment: false,
            cashValid: false,
            debtValid: false,
            totalBalance: 0,
          },
          financialSituation: {
            savingAccount: undefined,
            retirementAccount: undefined,
            stockAndBonds: undefined,
            giftFromRelative: undefined,
            loanAmount: undefined,
            salesOfRealEstate: undefined,
            other: undefined,
          },
        },
        estateEditState: 'view',
        state: MortgageRefinanceAssetsState.your_property,
      },
      DTI: {
        state: DTIState.notice,
        dti: 0,
        reconciled: false,
        dtiMaxAcceptable: 0.43,
      },
    },
  },
  bridge: {
    purchase: {
      name: 'BridgePurchase',
      preApproved: false,
      denialReason: void 0,
      state: BridgePurchaseState.starting,
      starting: {
        purpose: {
          values: {
            propertyNumber: Options.BridgePropertyNumberOpt.default,
            address: {
              formatAddress: '',
              aptNumber: '',
              state: '',
              street: '',
              city: '',
              postcode: '',
              errors: {},
              isValid: false,
            },
          },
          isValid: false,
        },
        property: {
          values: {
            propertyType: Options.PropertyOpt.default,
            propertyUnit: Options.PropertyUnitOpt.default,
            isConfirm: false,
          },
        },
        state: StartingState.purpose,
      },
      creditScore: {
        selfInfo: {
          firstName: '',
          lastName: '',
          phoneNumber: '',
          dateOfBirth: null,
          address: {
            formatAddress: '',
            aptNumber: '',
            state: '',
            street: '',
            city: '',
            postcode: '',
            errors: {},
            isValid: false,
          },
          ssn: '',
          authorizedCreditCheck: false,
          creditScore: 800,
          email: '',
          errors: {},
          isValid: false,
        },
        state: BridgeCreditScoreState.notice,
      },
      whereKnowUs: {
        reference: Options.ChannelOpt.default,
      },
      estimateRate: {
        purchasePrice: undefined,
        purchaseLoanAmount: undefined,
        isRehab: false,
        rehabCost: undefined,
        arv: undefined,
      },
    },
    refinance: {
      name: 'BridgeRefinance',
      preApproved: false,
      denialReason: void 0,
      state: BridgeRefinanceState.starting,
      starting: {
        purpose: {
          values: {
            propertyNumber: Options.BridgePropertyNumberOpt.default,
            address: {
              formatAddress: '',
              aptNumber: '',
              state: '',
              street: '',
              city: '',
              postcode: '',
              errors: {},
              isValid: false,
            },
          },
          isValid: false,
        },
        property: {
          values: {
            propertyType: Options.PropertyOpt.default,
            propertyUnit: Options.PropertyUnitOpt.default,
            isConfirm: false,
          },
        },
        state: StartingState.purpose,
      },
      creditScore: {
        selfInfo: {
          firstName: '',
          lastName: '',
          phoneNumber: '',
          dateOfBirth: null,
          address: {
            formatAddress: '',
            aptNumber: '',
            state: '',
            street: '',
            city: '',
            postcode: '',
            errors: {},
            isValid: false,
          },
          ssn: '',
          email: '',
          authorizedCreditCheck: false,
          creditScore: 799,
          errors: {},
          isValid: false,
        },
        state: BridgeCreditScoreState.notice,
      },
      whereKnowUs: {
        reference: Options.ChannelOpt.default,
      },
      estimateRate: {
        homeValue: undefined,
        balance: undefined,
        isCashOut: false,
        cashOutAmount: undefined,
        isCor: false,
        cor: undefined,
        arv: undefined,
      },
    },
  },
  pipelineTaskDefaultData: {
    [PipelineTaskKey.AI]: {
      taskName: PipelineTaskName[PipelineTaskKey.AI],
      taskId: '',
      taskStatus: PipelineTaskItemStatus.UNFINISHED,
      taskForm: {
        address: {
          formatAddress: '',
          aptNumber: '',
          state: '',
          street: '',
          city: '',
          postcode: '',
          errors: {},
          isValid: false,
        },
        bankName: '',
        accountName: '',
        routingNumber: '',
        accountNumber: '',
        accountType: '',
        documentFile: undefined,
      },
    },
    [PipelineTaskKey.BA]: {
      taskName: PipelineTaskName[PipelineTaskKey.BA],
      taskId: '',
      taskStatus: PipelineTaskItemStatus.UNFINISHED,
      taskForm: {
        address: {
          formatAddress: '',
          aptNumber: '',
          state: '',
          street: '',
          city: '',
          postcode: '',
          errors: {},
          isValid: false,
        },
        phone: '',
        email: '',
        title: '',
        fullName: '',
        company: '',
        documentFile: undefined,
      },
    },
    [PipelineTaskKey.LOA]: {
      taskName: PipelineTaskName[PipelineTaskKey.LOA],
      taskId: '',
      taskStatus: PipelineTaskItemStatus.UNFINISHED,
      taskForm: {
        address: {
          formatAddress: '',
          aptNumber: '',
          state: '',
          street: '',
          city: '',
          postcode: '',
          errors: {},
          isValid: false,
        },
        phone: '',
        email: '',
        title: '',
        fullName: '',
        company: '',
        documentFile: undefined,
      },
    },
    [PipelineTaskKey.REAA]: {
      taskName: PipelineTaskName[PipelineTaskKey.REAA],
      taskId: '',
      taskStatus: PipelineTaskItemStatus.UNFINISHED,
      taskForm: {
        address: {
          formatAddress: '',
          aptNumber: '',
          state: '',
          street: '',
          city: '',
          postcode: '',
          errors: {},
          isValid: false,
        },
        phone: '',
        email: '',
        title: '',
        fullName: '',
        company: '',
        documentFile: undefined,
      },
    },
    [PipelineTaskKey.BG]: {
      taskName: PipelineTaskName[PipelineTaskKey.BG],
      taskId: '',
      taskStatus: PipelineTaskItemStatus.UNFINISHED,
      taskForm: {
        taskFiles: [],
      },
    },
    [PipelineTaskKey.BL]: {
      taskName: PipelineTaskName[PipelineTaskKey.BL],
      taskId: '',
      taskStatus: PipelineTaskItemStatus.UNFINISHED,
      taskForm: {
        taskFiles: [],
      },
    },
    [PipelineTaskKey.BQ]: {
      taskName: PipelineTaskName[PipelineTaskKey.BQ],
      taskId: '',
      taskStatus: PipelineTaskItemStatus.UNFINISHED,
      taskForm: {
        licenses: [
          {
            ownerName: undefined,
            ssn: undefined,
            birthday: null,
            state: undefined,
            licenseType: Options.PipelineLicenseTypeOpt.default,
            license: undefined,
          },
        ],
        documentFile: undefined,
      },
    },
    [PipelineTaskKey.WF]: {
      taskName: PipelineTaskName[PipelineTaskKey.WF],
      taskId: '',
      taskStatus: PipelineTaskItemStatus.UNFINISHED,
      taskForm: {
        taskFiles: [],
      },
    },
  },
};
