import Head from 'next/head';

const Index = () => {
  return (
    <>
      <Head>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
      </Head>
    </>
  );
};

export default Index;
