import Head from 'next/head';

import { observer } from 'mobx-react-lite';

import { EntrancePage } from '@/views';

const Index = observer(() => {
  return (
    <>
      <Head>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
      </Head>
      <EntrancePage />
    </>
  );
});

export default Index;
