import Head from 'next/head';
import dynamic from 'next/dynamic';
import { CircularProgress } from '@mui/material';

import { observer } from 'mobx-react-lite';

const DynamicEntrance = dynamic(
  () => import('@/views/EntrancePage').then((mod) => mod.EntrancePage),
  {
    loading: () => (
      <div
        style={{
          width: '100vw',
          height: '100vh',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          minWidth: 375,
          minHeight: 667,
        }}
      >
        <CircularProgress />
      </div>
    ),
    ssr: false,
  },
);

const Index = observer(() => {
  return (
    <>
      <Head>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
      </Head>
      <DynamicEntrance />
    </>
  );
});

export default Index;
